sonar.projectKey=enddzone_servestead
sonar.organization=enddzone
sonar.projectName=servestead

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=backend/**/*_test.go
sonar.exclusions=.git/**,.github/**,.lavish/**,bin/**,dist/**,coverage.out,**/*_test.go,docs/**
sonar.coverage.exclusions=backend/setup.go,frontend/**/*
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
